#!/usr/bin/env bash
# Tranfers a file from our client to a server

# checks if the commandline argumnets are enough
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assignment
file_path="$1"
ip="$2"
username="$3"
ssh_key="$4"

# transfer file
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$ip:~/"
