#!/usr/bin/env bash
# script to install nginx web-01

# update and install
apt-get update
apt-get install -y nginx

# configure the server to listen to port 80
echo "sever {
	listen 80;
	location / {
		echo \"Hello World!\";
	}
}" > /etc/nginx/sites-available/default

# reload
/etc/init.d/nginx reload
