#!/usr/bin/env bash
# script to install nginx web-01

# update and install
apt-get update
apt-get install -y nginx

# configure the server to listen to port 80
sudo sed -i 's/listen 80;/g' /etc/nginx/sites-available/default
# Restart nginx without systemctl
sudo service nginx restart

#create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
