#!/usr/bin/env bash
# Configure your Nginx to /redirect_me is redirecting to another page.
# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx for redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name peterdev.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/;
    }

    location / {
        return 404;
    }
}
EOF

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test nginx configuration
nginx -t

# Restart nginx to apply changes
sudo service nginx restart
