#!/usr/bin/env bash
# configure both my webservers to return their host name
# update packages
sudo apt update

# instal nginx
sudo apt install -y nginx

# define custom header configuration
cat <<EOF > /etc/nginx/conf.d/custom_http_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name peterdev.tech;

    location / {
        add_header X-Served-By $HOSTNAME;
    }
}
EOF

# restart to to apply changes
sudo systemctl restart nginx
