#!/usr/bin/env bash
# installs and configures HAproxy on my lb-01 server
# update and install HAproxy
sudo apt update
sudo apt install -y haproxy

# configure HAproxy
echo "
backend my_backend
  balance roundrobin
  server web-1 498631-web-01:80 check
  server web-2 498631-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable HAproxy mangement via Init Script
sudo systemctl enable haproxy

# restart HAproxy
sudo systemctl restart haproxy
