#!/usr/bin/env bash
# installs and configures HAproxy on my lb-01 server
# update and install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# configure HAproxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
  balance roundrobin
  server web-1 498631-web-01:80 check
  server web-2 498631-web-02:80 check
EOF
# enable HAproxy mangement via Init Script
sudo sed -i 's/#ENABLED=0/ENABLED=1/' /etc/default/haproxy

# restart HAproxy
sudo service haproxy restart
