#!/usr/bin/env bash
# install mysql in server and checks version

# update package and install mysql
sudo apt update
sudo apt install mysql-server

# start mysql service
sudo service mysql start

# check mysql status
sudo service mysql status
