#!/usr/bin/env bash
# configures a server to listen to port 80

# the path to configuration file
nginx_conf="/etc/nginx/sites-enabled/default"

# server configuratio
server_block="
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv4only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}
}
"
# Check if Nginx is already running and listening on port 80
nginx_running=$(sudo netstat -tuln | grep ':80')

if [ -z "$nginx_running" ]; then
    # Nginx is not running or not listening on port 80
    echo "Nginx is not running or not listening on port 80. Attempting to start Nginx..."

    # Start Nginx
    sudo service nginx start

    # Wait for Nginx to start
    sleep 2

    # Check if Nginx is now listening on port 80
    nginx_running=$(sudo netstat -tuln | grep ':80')

    if [ -n "$nginx_running" ]; then
        echo "Nginx is now running and listening on port 80."
    else
        echo "Failed to start Nginx or Nginx is not listening on port 80. Please check Nginx's status and logs for errors."
    fi
else
    echo "Nginx is already running and listening on port 80."
fi

# check if nginx configuration file exists
if [ -f "$nginx_conf" ]; then
	# add server block to the configuration file
	echo "$server_block" | sudo tee -a "$nginx_conf" > /dev/null
fi
# restart nginx
sudo service nginx start
