#!/usr/bin/env bash
# configure server to listen to port 80

# Install Nginx if it's not installed
sudo apt-get update
sudo apt-get install -y nginx

# Check and remove any default configuration that may conflict
sudo rm /etc/nginx/sites-enabled/default

# Create a new Nginx server block file
cat << EOF | sudo tee /etc/nginx/sites-available/my_site
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Enable the new configuration
sudo ln -s /etc/nginx/sites-available/my_site /etc/nginx/sites-enabled/

# Check for any syntax errors in Nginx files
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx

# Check if Nginx is running and listening on port 80
sudo systemctl status nginx
netstat -plnt | grep ':80'
