#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes:


var1=0
while ((var1<=12)); do
	var=1
	echo "Hour: $var1"
	while ((var<60)); do
		echo "$var"
		((var+=1))
	done
	((var1+=1))
done
