#!/usr/bin/env bash
# fix apache server to curl port 80 and return a page containing Hello Holberton

sudo service apache2 start
echo "Listen 8080" | sudo tee -a /etc/apache2/ports.conf
sudo service apache2 restart
